#!/bin/bash

git config --global init.defaultBranch main
git config --global core.excludesfile $HOME/.gitignoreglobal
git config --global user.email ${_git_email}
git config --global user.name ${_git_user}