#!/bin/bash

alias ws="cd $HOME/workspace"
alias wsa="cd $HOME/workspace/android"
alias ezshrc="nano $HOME/.zshrc"
alias eppa="sudo nano /etc/apt/sources.list"

alias clearTrash="rm -rf $HOME/.local/share/Trash"

alias tarinfo='tar -ztvf $1'

# Docker
alias enableDocker="sudo systemctl enable docker"
alias disableDocker="sudo systemctl disable docker"

# Internet radio
alias mpgcadenaser="mpg123 http://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3"
alias mpgmegastar="mpg123 -@ http://megastar.cope.stream.flumotion.com/cope/megastar-low.mp3.m3u"
alias mpgrockfm="mpg123 -@ http://rockfm.cope.stream.flumotion.com/cope/rockfm-low.mp3.m3u"
alias mpg40p="mpg123 http://playerservices.streamtheworld.com/api/livestream-redirect/Los40.mp3"
alias mpg40c="mpg123 http://playerservices.streamtheworld.com/api/livestream-redirect/M80RADIO.mp3"
alias mpgtriplej="mpg123 -@ http://www.abc.net.au/res/streaming/audio/mp3/triplej.pls"
alias mpgbbc1="mpg123 -@ http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p"
alias mpgbbc2="mpg123 -@ http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p"
alias mpgbbc3="mpg123 -@ http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p"
alias mpgbbc4="mpg123 -@ http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p"
